var superpipe = require('superpipe')

exports.setupChannel = superpipe()
  .pipe('checkChannelPropertyName?', ['channel', 'service'])
  .pipe('setDefaultChannelHandlers?', 'channel')
  .pipe('bindChannelMethods?', ['channel', 'service'])
  .pipe('createChannelAdapter?', ['channel', 'service'], ['chnAdapter', 'chnNamespace'])
  .pipe('buildJoinHook?', 'channel', 'chnJoinHook')
  .pipe('buildAllowHook?', 'channel', 'chnAllowHook')
  .pipe('attachAllowHook?', ['chnAdapter', 'channel', 'chnJoinHook', 'chnAllowHook'])
  .pipe('attachEventHandlers?', ['chnAdapter', 'channel'], 'chnRepEvents')
